server:
  port: 8081
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    defaultSchema:
    maxPoolSize: 10
    url: jdbc:postgresql://shared.resources:5432/leagues
    username: user
    password: user
    liquibase:
     url: jdbc:postgresql://shared.resources:5432/leagues
     username: user
     password: user
  hibernate:
    hbm2ddl.method: none
    show_sql: false
    format_sql: false
    dialect: org.hibernate.dialect.PostgreSQL82Dialect
  liquibase:
   enabled: true
   drop-first: false
   change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
microservices:
  token-user: f745b9f103be4738a0d14605cccfaab7